### ISSUE TITLE
parser-library/parse.h: No such file or directory (Gcc11/Cmake 3.22)

### ISSUE THREAD

**Issue by melroy89** [gsauthof/pe-util#13]
(cross-)Compiling (to Windows) using **GCC11** and **Cmake 3.22** can't find the header?

```bash
gsauthof-pe-util-5b07cb3/peldd.cc:4:10: fatal error: parser-library/parse.h: No such file or directory
    4 | #include <parser-library/parse.h>
```

Are you sure you do not miss a [`target_include_directories()`](https://cmake.org/cmake/help/latest/command/target_include_directories.html) in your [CMakeLists.txt file](https://github.com/gsauthof/pe-util/blob/master/CMakeLists.txt)? Instead of this very strange `set_property()`

**Comment by gsauthof** [comment]
Are you sure that just using another cmake TMTOWTDI construct makes a difference for your issue?

You should include the exact steps you executed while cross-compiling such that others have a better chance at reproducing your issue.

I've never tried to cross-compile pe-util itself, until now.

It also fails for me on current Fedora 36, but with a different error:

```
~/scratch/pe-util $ mkdir build-cross
~/scratch/pe-util $ cd build-cross 
~/scratch/pe-util/build-cross $ mingw64-cmake -DCMAKE_BUILD_TYPE=Debug ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.
  
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
  
  
-- The CXX compiler identification is GNU 11.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done 
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Boost (missing: system filesystem) (found suitable version "1.75.0", minimum required is "1.54")
-- Configuring done-- Generating done
CMake Warning: 
  Manually-specified variables were not used by the project:

    BUILD_SHARED_LIBS
    CMAKE_INSTALL_LIBDIR
    INCLUDE_INSTALL_DIR
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
    
    
-- Build files have been written to: /home/juser/scratch/pe-util/build-cross
~/scratch/pe-util/build-cross $ mingw64-make
[ 25%] Building CXX object CMakeFiles/peldd.dir/peldd.cc.obj
[ 50%] Building CXX object CMakeFiles/peldd.dir/pe-parse/pe-parser-library/src/parse.cpp.obj
[ 75%] Building CXX object CMakeFiles/peldd.dir/pe-parse/pe-parser-library/src/buffer.cpp.obj/home/juser/scratch/pe-util/pe-parse/pe-parser-library/src/buffer.cpp:40:10: fatal error: sys/mman.h: No such file or directory   40 | #include <sys/mman.h>      |          ^~~~~~~~~~~~compilation terminated.make[2]: *** [CMakeFiles/peldd.dir/build.make:107: CMakeFiles/peldd.dir/pe-parse/pe-parser-library/src/buffer.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/peldd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

This is caused by the external dependency using the `WIN32` macro, but mingw just defines `_WIN32`, as expected.

Fix:

```
--- a/pe-parser-library/src/buffer.cpp
+++ b/pe-parser-library/src/buffer.cpp
@@ -28,7 +28,7 @@ THE SOFTWARE.
 // keep this header above "windows.h" because it contains many types
 #include <parser-library/parse.h>
 
-#ifdef WIN32
+#ifdef _WIN32
 
 #define WIN32_LEAN_AND_MEAN
 #define VC_EXTRALEAN
```

After fixing that it fails with a link error, because it can't find the boost libraries.  It fails late, because `find_package()` misses a `REQUIRED` keyword. Turns out that this is caused by a [cmake mingw bug](https://gitlab.kitware.com/cmake/cmake/-/issues/20587).

With a workaround my cross-compile finishes successfully.

**Comment by melroy89** [comment]
> You should include the exact steps you executed while cross-compiling such that others have a better chance at reproducing your issue

Compilation is done with `make pe-util MXE_TARGETS='x86_64-w64-mingw32.static' `, to cross compile towards windows.

See also https://github.com/mxe/mxe/pull/2714

**Comment by melroy89** [comment]
Sorry I was indeed not clear I forgot to mention that I was using www.mxe.cc for cross compiling. Again I'm using gcc11.

**Comment by melroy89** [comment]
It looks like the git sub module I was using is a newer version of pe-parser. I think a newer version, looking at: https://github.com/trailofbits/pe-parse/tree/master/pe-parser-library/include

Anyway the folder in the include directory is now called `pe-parse`. So your code will become:

```diff
-#include <parser-library/parse.h>
-#include <parser-library/nt-headers.h>
+#include <pe-parse/parse.h>
+#include <pe-parse/nt-headers.h>
```

Also still take my other comment serious. Try to improve your CMakeLists.txt file using  your [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html):

```diff
-set_property(TARGET peldd PROPERTY INCLUDE_DIRECTORIES
-    ${CMAKE_CURRENT_SOURCE_DIR}/pe-parse/pe-parser-library/include)
+target_include_directories(peldd SYSTEM PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/pe-parse/pe-parser-library/include)
```

**Comment by gsauthof** [comment]
Why do you thumbs down my reply where I address your report and I illustrate in much detail how you can cross-compile this software?

> Also still take my other comment serious. Try to improve your CMakeLists.txt file using your target_include_directories:

Well, I took and take your other comment seriously. However, you failed to show how this is an improvement to begin with. Nor what it has to do with your original problem. And why it isn't merely a syntactic variation that yields pretty much the same results.

Also, what's the point adding the `PUBLIC` keyword to an executable target ...

Lastly, by adding the `SYSTEM` keyword you actively suppress warnings in that code which is bad. So your change doesn't improve anything, it makes things worse.

> It looks like the git sub module I was using is a newer version of pe-parser.

Please note that I don't know anything about the mxe project and I don't know what they are doing to my software. So if they update the pe-parse submodule without making sure that everything still compiles and works  - then this would be a strange approach.

**Comment by melroy89** [comment]
Sorry thumb up was intended. The system keyword is up to you, but since you using pe-parse as a dependency you may not be interested in their warnings. But you could omit that, if you want.

Since it's a binary interface keyword could also be used (together with system) or private keyword.

Yeah, I understand mxe project may be new to you.
