### ISSUE TITLE
Can this be built with latest pe-parse?

### ISSUE THREAD

**Issue by tonytheodore** [gsauthof/pe-util#7]
Hi,

This looks like a really useful utility that I'd like to add to [MXE](https://github.com/mxe/mxe) but I'm having some build issues both using the latest pe-parse or going back to the pinned commit.

Before I spend too much time investigating, I thought I'd ask if this is known to work with later pe-parse?

Thanks.

**Comment by gsauthof** [comment]
I don't know if it builds with the latest pe-parse.

I've tested the build on a Fedora 26 system (fresh clone) and there it still builds fine with the pinned pe-parse:

    git clone https://github.com/gsauthof/pe-util.git
    cd pe-util
    git submodule update --init
    mkdir build
    cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make VERBOSE=1

In which environment do you have build problems?

**Comment by tonytheodore** [comment]
Thanks! All works well on macOS 10.13.3 (Darwin 17.4.0) with boost 1.60. 

The pinned pe-parse seemed to require functions from an earlier boost version, where newer pe-parse removes boost entirely - so I thought I'd start with the latter.
