### ISSUE TITLE
Can you make a release binary?

### ISSUE THREAD

**Issue by zedxxx** [gsauthof/pe-util#9]
I haven't Boost library on my system and can't build `peldd` by myself. So, can you provide a compiled binaries?

**Comment by zedxxx** [comment]
Here it is: [peldd_x86_64.zip](https://github.com/gsauthof/pe-util/files/2216209/peldd_x86_64.zip)

Compiled with: [MinGW Distro - nuwen.net](https://nuwen.net/mingw.html)

**Comment by gsauthof** [comment]
Didn't know that people are using this under Windows.

Just to clarify for others: the above link `https://github.com/gsauthof/pe-util/files/2216209/peldd_x86_64.zip` is just a file attachment to this issue, created by zedxxx. It's not an official release and I haven't looked at it. Thus, only download and use it if you trust zedxxx.

When time allows, I'll look into creating an official peldd binary release for windows - linking it then from the github project page.
